### ISSUE TITLE
Pozice svetla

### ISSUE THREAD

**Issue by iond2v** [zdenek-biberle/gpu-real-time-shadows#2]
nemelo by mit svetlo pozici 1,1,1 misto -1, -1, -1??
Ono to vypada, ze ten stin se kresli od svetla ke stinicimu, ale melo by to byt naopak.. od stiniciho dal.
Tady na obrazku je to videt.. osvetleny je vrsek, ale svetlo je dole..
![nema se to spis rozbihat](https://cloud.githubusercontent.com/assets/8090765/12003903/f986815c-ab32-11e5-870f-73f690223d2f.png)

**Comment by zdenek-biberle** [comment]
Teď si už úplně nepamatuju, ale mám pocit, že jsme (jsem?) tam nějak míchali pozici a směr.

**Comment by iond2v** [comment]
Takze je to tim, ze se nepocita s lightPosition pri vytvareni thoho volume, ale jen s extrusion vectorem z delky a smeru svetla, takze perspektiva se postara o to zuzeni... Jinak zbytek je uz spravne

**Comment by iond2v** [comment]
cpuImpl ted spravne extruduje dle pozice svetla
