### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [zdenek-biberle/gpu-real-time-shadows#4]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114332393-be899300-9b78-11eb-9d85-c7a607dea423.png)

thank you  
best regards to you  
William

**Comment by iond2v** [comment]
Hello.. it says invalid amount of parameters.
It needs two. Scene model and model to create shadows for. I hope it helps. It is an old school project, so no guarantees..
